# Generated by Django 5.2.9 on 2025-12-24 19:22

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Acquisition',
            fields=[
                ('id_parcel', models.AutoField(primary_key=True, serialize=False)),
                ('kode_parcel', models.TextField()),
                ('nama_pemilik', models.TextField()),
                ('desa', models.TextField()),
                ('luas', models.FloatField()),
                ('status', models.TextField()),
                ('jumlah_bebas', models.FloatField()),
                ('biaya_pembebasan', models.IntegerField()),
                ('tanggal_negosiasi', models.DateField()),
                ('geom', django.contrib.gis.db.models.fields.PolygonField(srid=4326)),
            ],
            options={
                'verbose_name': 'Acquisition',
                'verbose_name_plural': 'Acquisition',
                'db_table': 'tbl_acquisition',
            },
        ),
        migrations.CreateModel(
            name='HistoryAcquisition',
            fields=[
                ('id_history', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.TextField()),
                ('deskripsi', models.TextField()),
                ('id_parcel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='histories', to='backend.acquisition')),
            ],
            options={
                'verbose_name': 'History_acquisition',
                'verbose_name_plural': 'History_acquisitions',
                'db_table': 'tbl_history_acquisition',
            },
        ),
    ]
