# Generated by Django 5.2.9 on 2025-12-24 20:04

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LandInventory',
            fields=[
                ('id_lahan', models.AutoField(primary_key=True, serialize=False)),
                ('kode_lahan', models.CharField(max_length=50)),
                ('nama_lokasi', models.TextField()),
                ('no_sertif', models.TextField()),
                ('geom', django.contrib.gis.db.models.fields.PointField(srid=4326)),
            ],
            options={
                'verbose_name': 'LandInventory',
                'verbose_name_plural': 'LandInventories',
                'db_table': 'tbl_land_inventory',
            },
        ),
        migrations.CreateModel(
            name='LandKategori',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.PositiveSmallIntegerField(unique=True)),
                ('label', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name': 'land_inventory_categories',
                'verbose_name_plural': 'land_inventory_categories',
                'db_table': 'ref_land_inventory_category',
            },
        ),
        migrations.CreateModel(
            name='LandStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.PositiveSmallIntegerField(unique=True)),
                ('label', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name': 'Ref_land_invetory_status',
                'verbose_name_plural': 'Ref_land_invetory_status',
                'db_table': 'ref_land_invetory_status',
            },
        ),
        migrations.CreateModel(
            name='LandInventoryDocument',
            fields=[
                ('id_document', models.AutoField(primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='landInventoryDocument')),
                ('id_lahan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='backend.landinventory')),
            ],
            options={
                'verbose_name': 'Land Inventory Document',
                'verbose_name_plural': 'Land Inventory Documents',
                'db_table': 'ref_land_inventory_document',
            },
        ),
        migrations.AddField(
            model_name='landinventory',
            name='kategori',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='kateogri', to='backend.landkategori'),
        ),
        migrations.AddField(
            model_name='landinventory',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='status', to='backend.landstatus'),
        ),
    ]
