# Generated by Django 5.2.9 on 2025-12-25 07:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_landinventory_landkategori_landstatus_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LandAcquisitionProject',
            fields=[
                ('id_project', models.AutoField(primary_key=True, serialize=False)),
                ('nama_project', models.TextField()),
                ('tanggal_dibuat', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='LandInventoryThemeMap',
            fields=[
                ('id_theme_map', models.AutoField(primary_key=True, serialize=False)),
                ('nama_map', models.TextField()),
                ('tbl_name', models.TextField()),
            ],
            options={
                'verbose_name': 'Land Inventory Theme Map',
                'verbose_name_plural': 'Land Inventory Theme Maps',
                'db_table': 'tbl_land_inventory_theme_map',
            },
        ),
        migrations.AddField(
            model_name='acquisition',
            name='id_project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AcquisitonProject', to='backend.landacquisitionproject'),
        ),
    ]
