# Generated by Django 5.2.9 on 2025-12-25 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_landacquisitionproject_landinventorythememap_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='landacquisitionproject',
            name='owner_project',
            field=models.TextField(default='Anonim'),
            preserve_default=False,
        ),
    ]
