# Generated by Django 5.2.9 on 2025-12-25 18:59

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_landacquisitionproject_owner_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='PolygonPersil',
            fields=[
                ('id_persil', models.AutoField(primary_key=True, serialize=False)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
            options={
                'verbose_name': 'Polygon Persil',
                'verbose_name_plural': 'Polygon Persils',
                'db_table': 'tbl_persil',
            },
        ),
        migrations.AlterModelOptions(
            name='landacquisitionproject',
            options={'verbose_name': 'Land Acquisition Project', 'verbose_name_plural': 'Land Acquisition Projects'},
        ),
        migrations.RemoveField(
            model_name='acquisition',
            name='geom',
        ),
        migrations.RemoveField(
            model_name='landinventory',
            name='geom',
        ),
        migrations.AlterField(
            model_name='historyacquisition',
            name='id_parcel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='histories', to='backend.acquisition'),
        ),
        migrations.AlterField(
            model_name='landacquisitionproject',
            name='tanggal_dibuat',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterModelTable(
            name='landacquisitionproject',
            table='tbl_land_acquisition_project',
        ),
        migrations.AddField(
            model_name='acquisition',
            name='id_persil',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='acquisition', to='backend.polygonpersil'),
        ),
        migrations.AddField(
            model_name='landacquisitionproject',
            name='id_persil',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='projects', to='backend.polygonpersil'),
        ),
        migrations.AddField(
            model_name='landinventory',
            name='id_persil',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='persilGeom', to='backend.polygonpersil'),
        ),
    ]
