# Generated by Django 5.2.9 on 2025-12-25 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_polygonpersil_alter_landacquisitionproject_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acquisition',
            name='biaya_pembebasan',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='acquisition',
            name='jumlah_bebas',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='acquisition',
            name='luas',
            field=models.FloatField(default=0, null=True),
        ),
    ]
