# Generated by Django 5.2.9 on 2025-12-25 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_alter_acquisition_biaya_pembebasan_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acquisition',
            name='tanggal_negosiasi',
            field=models.DateField(blank=True, null=True),
        ),
    ]
