# Generated by Django 5.2.9 on 2025-12-30 17:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_alter_acquisition_tanggal_negosiasi'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LandAcquisitionProject',
            new_name='Project',
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'verbose_name': 'Project', 'verbose_name_plural': 'Projects'},
        ),
        migrations.AddField(
            model_name='landinventory',
            name='id_project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ProjectInventory', to='backend.project'),
        ),
        migrations.AlterField(
            model_name='acquisition',
            name='id_project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ProjectAcquisition', to='backend.project'),
        ),
        migrations.AlterModelTable(
            name='landinventorydocument',
            table='tbl_land_inventory_document',
        ),
        migrations.AlterModelTable(
            name='project',
            table='tbl_project',
        ),
        migrations.CreateModel(
            name='LandInventoryRaster',
            fields=[
                ('id_raster', models.AutoField(primary_key=True, serialize=False)),
                ('store_name', models.TextField()),
                ('nama', models.TextField()),
                ('raster_path', models.FileField(upload_to='../upload/raster')),
                ('id_project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Project', to='backend.project')),
            ],
            options={
                'verbose_name': 'Land Inventory Raster',
                'verbose_name_plural': 'Land Inventory Rasters',
                'db_table': 'tbl_land_inventory_raster',
            },
        ),
    ]
