# Generated by Django 5.2.9 on 2025-12-30 17:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_alter_project_options_landinventory_id_project_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acquisition',
            name='id_project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ProjectAcquisition', to='backend.project'),
        ),
    ]
