# Generated by Django 5.2.9 on 2025-12-30 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_alter_acquisition_id_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='landinventorydocument',
            name='nama_dokumen',
            field=models.TextField(default='dokumen'),
            preserve_default=False,
        ),
    ]
