# Generated by Django 5.2.9 on 2025-12-31 08:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_landinventorydocument_nama_dokumen'),
    ]

    operations = [
        migrations.AddField(
            model_name='landinventorythememap',
            name='id_project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ProjectThemeMap', to='backend.project'),
        ),
        migrations.AlterField(
            model_name='landinventoryraster',
            name='id_project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ProjectRaster', to='backend.project'),
        ),
    ]
