# Generated by Django 5.2.9 on 2025-12-31 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0011_landinventorythememap_id_project_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landinventoryraster',
            name='raster_path',
            field=models.FileField(upload_to='raster/'),
        ),
    ]
