# Generated by Django 5.2.9 on 2025-12-31 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0012_alter_landinventoryraster_raster_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='landinventorythememap',
            name='shp_path',
            field=models.FileField(default='/', upload_to='themeMap'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='landinventorythememap',
            name='tbl_name',
            field=models.TextField(editable=False, unique=True),
        ),
    ]
