# Generated by Django 5.2.9 on 2025-12-31 20:33

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0013_landinventorythememap_shp_path_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='id_persil',
        ),
        migrations.AddField(
            model_name='project',
            name='geom',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(default="MULTIPOLYGON (((114.56543 -4.039618, 114.56543 1.01069, 119.267578 1.01069, 119.267578 -4.039618, 114.56543 -4.039618)))",srid=4326),
            preserve_default=False,
        ),
    ]
