# Generated by Django 5.2.9 on 2026-01-01 19:43

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0014_remove_project_id_persil_project_geom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='polygonpersil',
            name='geom',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326),
        ),
    ]
