# Generated by Django 5.2.9 on 2026-01-01 19:46

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0015_alter_polygonpersil_geom'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='acquisition',
            name='id_persil',
        ),
        migrations.AddField(
            model_name='acquisition',
            name='geom',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326),
        ),
    ]
