# Generated by Django 5.2.9 on 2026-01-04 19:53

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0017_alter_acquisition_geom_alter_polygonpersil_geom_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcquisitionAsset',
            fields=[
                ('id_parcel_asset', models.AutoField(primary_key=True, serialize=False)),
                ('id_asset', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'verbose_name': 'Acquisition_asset',
                'verbose_name_plural': 'Acquisition_assets',
                'db_table': 'tbl_acquisition_asset',
            },
        ),
        migrations.RemoveField(
            model_name='landinventory',
            name='id_persil',
        ),
        migrations.AlterModelOptions(
            name='landinventoryraster',
            options={'verbose_name': 'Land Inventory Raster', 'verbose_name_plural': 'Land Inventory Ras`ters'},
        ),
        migrations.AddField(
            model_name='acquisition',
            name='NIB_Baru',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='landinventory',
            name='geom',
            field=django.contrib.gis.db.models.fields.GeometryField(blank=True, null=True, srid=4326),
        ),
        migrations.AddField(
            model_name='landinventorythememap',
            name='type',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='acquisition',
            name='id_asset',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='Acquisition_asset', to='backend.acquisitionasset'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='PolygonPersil',
        ),
    ]
