# Generated by Django 5.2.9 on 2026-01-06 10:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0018_acquisitionasset_remove_landinventory_id_persil_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acquisition',
            name='biaya_pembebasan',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='acquisition',
            name='desa',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='acquisition',
            name='id_asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Acquisition_asset', to='backend.acquisitionasset'),
        ),
        migrations.AlterField(
            model_name='acquisition',
            name='jumlah_bebas',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='acquisition',
            name='kode_parcel',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='acquisition',
            name='luas',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='acquisition',
            name='nama_pemilik',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='acquisition',
            name='status',
            field=models.TextField(blank=True, null=True),
        ),
    ]
