# Generated by Django 5.2.9 on 2026-01-06 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0019_alter_acquisition_biaya_pembebasan_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acquisitionasset',
            name='id_asset',
            field=models.TextField(blank=True, null=True),
        ),
    ]
