# Generated by Django 5.2.9 on 2026-01-06 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0020_alter_acquisitionasset_id_asset'),
    ]

    operations = [
        migrations.AddField(
            model_name='landinventorythememap',
            name='style',
            field=models.TextField(blank=True, null=True),
        ),
    ]
