# Generated by Django 5.2.9 on 2026-01-07 12:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0021_landinventorythememap_style'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landinventory',
            name='kategori',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, related_name='kateogri', to='backend.landkategori'),
        ),
        migrations.AlterField(
            model_name='landinventory',
            name='kode_lahan',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='landinventory',
            name='nama_lokasi',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='landinventory',
            name='no_sertif',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='landinventory',
            name='status',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, related_name='status', to='backend.landstatus'),
        ),
    ]
