# Generated by Django 5.2.9 on 2026-01-07 12:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0022_alter_landinventory_kategori_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landinventory',
            name='kategori',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='kateogri', to='backend.landkategori'),
        ),
        migrations.AlterField(
            model_name='landinventory',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='status', to='backend.landstatus'),
        ),
    ]
