# Generated by Django 5.2.9 on 2026-01-07 14:50

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0023_alter_landinventory_kategori_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='basemap',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='batas_admin',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='iupk',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='ProjectDetail',
            fields=[
                ('id_project_detail', models.AutoField(primary_key=True, serialize=False)),
                ('nama_site', models.TextField(default='Site', null=True)),
                ('geom', django.contrib.gis.db.models.fields.GeometryField(srid=4326)),
                ('id_project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ProjectDetail', to='backend.project')),
            ],
            options={
                'db_table': 'tbl_project_detail',
            },
        ),
    ]
