# Generated by Django 5.2.9 on 2026-01-07 14:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0024_project_basemap_project_batas_admin_project_iupk_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectdetail',
            name='id_project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='project_details', to='backend.project'),
        ),
    ]
