# Generated by Django 5.2.9 on 2026-01-08 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0026_historyacquisition_date_created_alter_project_geom'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='date_end',
            field=models.DateField(default='2000-01-01'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='date_start',
            field=models.DateField(default='2000-01-01'),
            preserve_default=False,
        ),
    ]
